//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------

namespace seoWebApplication.admin.catalog {
    
    
    public partial class departments {
        
        /// <summary>
        /// cgvDepartments control.
        /// </summary>
        /// <remarks>
        /// Auto-generated field.
        /// To modify move field declaration from designer file to code-behind file.
        /// </remarks>
        protected global::System.Web.UI.WebControls.GridView cgvDepartments;
        
        /// <summary>
        /// Master property.
        /// </summary>
        /// <remarks>
        /// Auto-generated property.
        /// </remarks>
        public new seoWebApplication.seoWebAppAdminEditGrid Master {
            get {
                return ((seoWebApplication.seoWebAppAdminEditGrid)(base.Master));
            }
        }
    }
}
